import { EMBEDDING_SOURCES, MEMORIES_KEY } from '../constants.js';
import { getSTVectorRequestBody, getSTVectorSource, purgeSTCollection } from '../services/st-vector.js';
import { getSessionSignal } from '../state.js';
import { getCurrentChatId, getOpenVaultData, saveOpenVaultData } from '../store/chat-data.js';
import { clearStSynced, deleteEmbedding, hasEmbedding, isStSynced } from '../utils/embedding-codec.js';
import { logDebug, logInfo, logWarn } from '../utils/logging.js';

/**
 * Enumerate every record that can own an embedding. Keeping this list in one
 * place prevents graph edges from being skipped by one migration path.
 * @param {Object} data - OpenVault chat data
 * @returns {Object[]}
 */
function getEmbeddingItems(data) {
    const memories = data?.[MEMORIES_KEY]?.length > 0 ? data[MEMORIES_KEY] : [];
    return [
        ...memories,
        ...Object.values(data?.graph?.nodes || {}),
        ...Object.values(data?.graph?.edges || {}),
        ...Object.values(data?.communities || {}),
    ];
}

/**
 * Check whether a migration still belongs to the chat it started in.
 * @param {string|null} expectedChatId - Chat ID captured before awaiting
 * @returns {boolean}
 */
function isExpectedChat(expectedChatId) {
    return expectedChatId === null || getCurrentChatId() === expectedChatId;
}

/**
 * Check both the chat ID and session generation. The signal catches a
 * chat A → B → A transition where the string ID alone would look current.
 * @param {string|null} expectedChatId - Chat ID captured before awaiting
 * @param {AbortSignal} signal - Session signal captured before awaiting
 * @returns {boolean}
 */
function isCurrentSession(expectedChatId, signal) {
    return !signal.aborted && isExpectedChat(expectedChatId);
}

/**
 * Get the current ST Vector Storage fingerprint (source + model) from ST settings.
 * Used to detect when the user changes vectorization settings on the ST side.
 * @returns {{source: string, model: string}} Current ST vector source and model
 */
export function getStVectorFingerprint() {
    const source = getSTVectorSource();
    const body = getSTVectorRequestBody(source);
    return { source, model: body.model || '' };
}

/**
 * Stamp ST Vector Storage fingerprint onto chat data after successful sync.
 * Call this after inserting items into ST so mismatch detection works on next load.
 * @param {Object} data - OpenVault chat data (chatMetadata.openvault)
 */
export function stampStVectorFingerprint(data) {
    if (!data) return;
    const fp = getStVectorFingerprint();
    data.st_vector_source = fp.source;
    data.st_vector_model = fp.model;
}

/**
 * Check if the ST Vector fingerprint (source + model) has changed.
 * @param {Object} data - OpenVault chat data
 * @returns {boolean} True if ST-side settings changed since last sync
 */
function _hasStVectorMismatch(data) {
    // No fingerprint stored yet — not a mismatch (first sync will stamp it)
    if (!data.st_vector_source && !data.st_vector_model) {
        // But if items are already synced, treat as mismatch (legacy data)
        const hasSynced = _hasSyncedItems(data);
        return hasSynced;
    }
    const fp = getStVectorFingerprint();
    return data.st_vector_source !== fp.source || data.st_vector_model !== fp.model;
}

/**
 * Check if any items have the _st_synced flag.
 * @param {Object} data - OpenVault chat data
 * @returns {boolean}
 */
function _hasSyncedItems(data) {
    for (const item of getEmbeddingItems(data)) {
        if (isStSynced(item)) return true;
    }
    return false;
}

/**
 * Clear all ST sync flags and fingerprint from data.
 * @param {Object} data - OpenVault chat data
 * @returns {number} Number of sync flags cleared
 */
function _clearAllStSyncFlags(data) {
    let count = 0;
    for (const item of getEmbeddingItems(data)) {
        if (isStSynced(item)) {
            clearStSynced(item);
            count++;
        }
    }
    delete data.st_vector_source;
    delete data.st_vector_model;
    return count;
}

/**
 * Count total embeddings across memories, graph nodes, and communities.
 * @param {Object} data - OpenVault chat data
 * @returns {number}
 */
function _countEmbeddings(data) {
    let count = 0;
    for (const item of getEmbeddingItems(data)) {
        if (hasEmbedding(item)) count++;
    }
    return count;
}

/**
 * Check if stored embeddings were generated by a different model.
 * If mismatch detected, wipe all embeddings and update the model tag.
 * For ST Vector Storage, also detects source/model changes on the ST side.
 *
 * @param {Object} data - OpenVault chat data (chatMetadata.openvault)
 * @param {string} currentModelId - Currently selected embedding source
 * @returns {Promise<number>} Number of embeddings/sync-flags wiped (0 = no mismatch)
 */
export async function invalidateStaleEmbeddings(data, currentModelId) {
    if (!data || !currentModelId) return 0;
    const expectedChatId = getCurrentChatId();
    const signal = getSessionSignal();
    if (!isCurrentSession(expectedChatId, signal)) return 0;

    const hasAnyEmbedding = _countEmbeddings(data) > 0;

    // No tag yet
    if (!data.embedding_model_id) {
        if (!hasAnyEmbedding) {
            // Brand new chat — just stamp
            data.embedding_model_id = currentModelId;
            if (currentModelId === EMBEDDING_SOURCES.ST_VECTOR) {
                stampStVectorFingerprint(data);
            }
            return 0;
        }
        // Legacy chat with embeddings but no tag → fall through to wipe
    }

    // Same OV source — but if ST Vector, also check ST-side fingerprint
    if (data.embedding_model_id === currentModelId) {
        if (currentModelId === EMBEDDING_SOURCES.ST_VECTOR && _hasStVectorMismatch(data)) {
            // ST source/model changed — purge the originating collection before
            // mutating the record, then re-check the chat before stamping it.
            const oldSource = data.st_vector_source || 'unknown';
            const oldModel = data.st_vector_model || 'unknown';
            const fp = getStVectorFingerprint();

            // Purge old ST collection (best-effort, don't block on failure)
            try {
                await purgeSTCollection(expectedChatId || 'default');
            } catch (e) {
                logWarn(`Failed to purge old ST collection: ${e.message}`);
            }
            if (!isCurrentSession(expectedChatId, signal)) return 0;

            const cleared = _clearAllStSyncFlags(data);

            // Stamp new fingerprint
            stampStVectorFingerprint(data);

            logInfo(
                `ST vector source changed (${oldSource}/${oldModel} → ${fp.source}/${fp.model}). Cleared ${cleared} sync flags.`
            );
            return cleared;
        }
        return 0;
    }

    // MISMATCH — wipe everything
    const oldModel = data.embedding_model_id || 'unknown';
    let count = 0;

    // Purge the old external collection before clearing the originating chat's
    // state. If the chat changes while the request is in flight, leave the old
    // record untouched and let the new chat continue its own migration.
    if (oldModel === EMBEDDING_SOURCES.ST_VECTOR) {
        try {
            await purgeSTCollection(expectedChatId || 'default');
        } catch (e) {
            logWarn(`Failed to purge old ST collection: ${e.message}`);
        }
        if (!isCurrentSession(expectedChatId, signal)) return 0;
    }

    for (const item of getEmbeddingItems(data)) {
        if (hasEmbedding(item)) {
            deleteEmbedding(item);
            count++;
        }
    }

    // Also clear ST sync flags
    const syncCleared = _clearAllStSyncFlags(data);
    count += syncCleared;

    data.embedding_model_id = currentModelId;
    if (currentModelId === EMBEDDING_SOURCES.ST_VECTOR) {
        stampStVectorFingerprint(data);
    }

    logInfo(`Embedding model changed (${oldModel} → ${currentModelId}). Wiped ${count} embeddings.`);
    return count;
}

/**
 * Delete embeddings from current chat's memories
 * @returns {Promise<number>} Number of embeddings deleted
 */
export async function deleteCurrentChatEmbeddings() {
    const data = getOpenVaultData();
    if (!data || !data[MEMORIES_KEY]) {
        return 0;
    }
    const expectedChatId = getCurrentChatId();
    const signal = getSessionSignal();
    if (!isCurrentSession(expectedChatId, signal)) return 0;

    let count = 0;
    for (const memory of data[MEMORIES_KEY]) {
        if (!isCurrentSession(expectedChatId, signal)) return 0;
        if (hasEmbedding(memory)) {
            deleteEmbedding(memory);
            count++;
        }
    }

    if (count > 0) {
        if (!(await saveOpenVaultData(expectedChatId))) {
            return 0;
        }
        logDebug(`Deleted ${count} embeddings`);
    }

    return count;
}
