#!/usr/bin/env node
/**
 * Generate src/types.d.ts from Zod schemas
 * Run via: npm run generate-types
 *
 * Uses the same _setTestOverride pattern as tests to mock CDN imports
 * so Node.js can import browser-targeted schema files.
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// --- 1. Mock CDN imports for Node.js ---
// Same pattern used in tests: set up global override before importing source files

if (!globalThis.__openvault_cdn_test_overrides) {
    globalThis.__openvault_cdn_test_overrides = new Map();
}

// Provide local zod for CDN mock
const { z } = await import('zod');
globalThis.__openvault_cdn_test_overrides.set('zod', { z });

// --- 2. Dynamically import zod-to-ts (ESM) ---
const { zodToTs, printNode, createAuxiliaryTypeStore } = await import('zod-to-ts');

// --- 2.5. Create auxiliary type store (required by zod-to-ts) ---
const auxiliaryTypeStore = createAuxiliaryTypeStore();

// --- 3. Import schemas from browser-accessible source files ---

const {
    MemorySchema,
    GraphNodeSchema,
    GraphEdgeSchema,
    GraphDataSchema,
    ScoreBreakdownSchema,
    ScoredMemorySchema,
    BaseEntitySchema,
    BaseRelationshipSchema,
    EventSchema,
    EventExtractionSchema,
    CharacterDataSchema,
    ReflectionStateSchema,
    GlobalWorldStateSchema,
    CommunitySummarySchema,
    OpenVaultDataSchema,
    StVectorItemSchema,
    ScoringConfigSchema,
    QueryConfigSchema,
} = await import('../src/store/schemas.js');

// --- 4. Map: Type Name -> Zod Schema ---

const typeMappings = [
    { name: 'Memory', schema: MemorySchema },
    { name: 'GraphNode', schema: GraphNodeSchema },
    { name: 'GraphEdge', schema: GraphEdgeSchema },
    { name: 'GraphData', schema: GraphDataSchema },
    { name: 'ScoreBreakdown', schema: ScoreBreakdownSchema },
    { name: 'ScoredMemory', schema: ScoredMemorySchema },
    { name: 'Entity', schema: BaseEntitySchema },      // Use base schema for types
    { name: 'Relationship', schema: BaseRelationshipSchema },
    { name: 'ExtractedEvent', schema: EventSchema },
    { name: 'EventExtraction', schema: EventExtractionSchema },
    { name: 'CharacterData', schema: CharacterDataSchema },
    { name: 'ReflectionState', schema: ReflectionStateSchema },
    { name: 'GlobalWorldState', schema: GlobalWorldStateSchema },
    { name: 'CommunitySummary', schema: CommunitySummarySchema },
    { name: 'OpenVaultData', schema: OpenVaultDataSchema },
    { name: 'StVectorItem', schema: StVectorItemSchema },
    { name: 'ScoringConfig', schema: ScoringConfigSchema },
    { name: 'QueryConfig', schema: QueryConfigSchema },
];

// --- 5. Generate the .d.ts file ---

const OUTPUT_PATH = path.resolve(__dirname, '../src/types.d.ts');

async function generateTypes() {
    const timestamp = new Date().toISOString();
    let dtsContent = `// AUTO-GENERATED BY scripts/generate-types.js
// Generated at: ${timestamp}
// DO NOT EDIT DIRECTLY. Update src/store/schemas.js instead.

`;

    for (const { name, schema } of typeMappings) {
        const { node } = zodToTs(schema, { name, auxiliaryTypeStore });
        const typeDef = printNode(node);
        dtsContent += `export type ${name} = ${typeDef};\n\n`;
    }

    // Add type-only export marker
    dtsContent += `// End of generated types\n`;

    await fs.writeFile(OUTPUT_PATH, dtsContent, 'utf-8');
    console.log(`Generated ${typeMappings.length} types in ${OUTPUT_PATH}`);
}

generateTypes().catch(err => {
    console.error('Type generation failed:', err.message);
    process.exit(1);
});
