// AUTO-GENERATED BY scripts/generate-types.js
// DO NOT EDIT DIRECTLY. Update src/store/schemas.js instead.

export type Memory = {
    id: string;
    summary: string;
    importance: number;
    embedding?: number[] | undefined;
    message_id: number;
    timestamp: number;
    witnesses?: string[] | undefined;
    type?: ("event" | "reflection" | "global_synthesis") | undefined;
    level?: number | undefined;
    tokens: string[];
    message_ids?: number[] | undefined;
    mentions?: number | undefined;
    retrieval_hits?: number | undefined;
    archived?: boolean | undefined;
    _st_synced?: boolean | undefined;
    _proxyVectorScore?: number | undefined;
};

export type GraphNode = {
    name: string;
    type: "PERSON" | "PLACE" | "ORGANIZATION" | "OBJECT" | "CONCEPT";
    description: string;
    mentions: number;
    embedding?: number[] | undefined;
    embedding_b64?: string | undefined;
    aliases?: string[] | undefined;
    _st_synced?: boolean | undefined;
};

export type GraphEdge = {
    source: string;
    target: string;
    description: string;
    weight: number;
    _descriptionTokens?: number | undefined;
    embedding?: number[] | undefined;
    embedding_b64?: string | undefined;
    _st_synced?: boolean | undefined;
};

export type GraphData = {
    nodes: {
        [key: string]: {
            name: string;
            type: "PERSON" | "PLACE" | "ORGANIZATION" | "OBJECT" | "CONCEPT";
            description: string;
            mentions: number;
            embedding?: number[] | undefined;
            embedding_b64?: string | undefined;
            aliases?: string[] | undefined;
            _st_synced?: boolean | undefined;
        };
    };
    edges: {
        [key: string]: {
            source: string;
            target: string;
            description: string;
            weight: number;
            _descriptionTokens?: number | undefined;
            embedding?: number[] | undefined;
            embedding_b64?: string | undefined;
            _st_synced?: boolean | undefined;
        };
    };
    _mergeRedirects?: {
        [key: string]: string;
    } | undefined;
    _edgesNeedingConsolidation?: string[] | undefined;
};

export type ScoreBreakdown = {
    total: number;
    base: number;
    baseAfterFloor: number;
    recencyPenalty: number;
    vectorBonus: number;
    vectorSimilarity: number;
    bm25Bonus: number;
    bm25Score: number;
    distance: number;
    importance: number;
    hitDamping?: number | undefined;
    frequencyFactor?: number | undefined;
};

export type ScoredMemory = {
    memory: {
        id: string;
        summary: string;
        importance: number;
        embedding?: number[] | undefined;
        message_id: number;
        timestamp: number;
        witnesses?: string[] | undefined;
        type?: ("event" | "reflection" | "global_synthesis") | undefined;
        level?: number | undefined;
        tokens: string[];
        message_ids?: number[] | undefined;
        mentions?: number | undefined;
        retrieval_hits?: number | undefined;
        archived?: boolean | undefined;
        _st_synced?: boolean | undefined;
        _proxyVectorScore?: number | undefined;
    };
    score: number;
    breakdown: {
        total: number;
        base: number;
        baseAfterFloor: number;
        recencyPenalty: number;
        vectorBonus: number;
        vectorSimilarity: number;
        bm25Bonus: number;
        bm25Score: number;
        distance: number;
        importance: number;
        hitDamping?: number | undefined;
        frequencyFactor?: number | undefined;
    };
};

export type Entity = {
    /** Entity name, capitalized */
    name: string;
    type: "PERSON" | "PLACE" | "ORGANIZATION" | "OBJECT" | "CONCEPT";
    /** Comprehensive description of the entity */
    description: string;
};

export type Relationship = {
    /** Source entity name */
    source: string;
    /** Target entity name */
    target: string;
    /** Description of the relationship */
    description: string;
};

export type ExtractedEvent = {
    summary: string;
    importance: number;
    characters_involved: string[];
    witnesses: string[];
    location: string | null;
    is_secret: boolean;
    emotional_impact: {
        [key: string]: any;
    } | undefined;
    relationship_impact: {
        [key: string]: any;
    } | undefined;
};

export type EventExtraction = {
    events: {
        summary: string;
        importance: number;
        characters_involved: string[];
        witnesses: string[];
        location: string | null;
        is_secret: boolean;
        emotional_impact: {
            [key: string]: any;
        } | undefined;
        relationship_impact: {
            [key: string]: any;
        } | undefined;
    }[];
};

export type CharacterData = {
    firstSeen?: number | undefined;
    lastSeen?: number | undefined;
    mentionCount?: number | undefined;
};

export type ReflectionState = {
    lastMessageId?: number | undefined;
    reflectionCount?: number | undefined;
};

export type GlobalWorldState = {
    summary: string;
    last_updated: number;
    community_count: number;
};

export type CommunitySummary = {
    id: string;
    title: string;
    summary: string;
    entities?: string[] | undefined;
    findings?: string[] | undefined;
    last_updated?: number | undefined;
};

export type OpenVaultData = {
    schema_version: number;
    memories?: {
        id: string;
        summary: string;
        importance: number;
        embedding?: number[] | undefined;
        message_id: number;
        timestamp: number;
        witnesses?: string[] | undefined;
        type?: ("event" | "reflection" | "global_synthesis") | undefined;
        level?: number | undefined;
        tokens: string[];
        message_ids?: number[] | undefined;
        mentions?: number | undefined;
        retrieval_hits?: number | undefined;
        archived?: boolean | undefined;
        _st_synced?: boolean | undefined;
        _proxyVectorScore?: number | undefined;
    }[] | undefined;
    characters?: {
        [key: string]: {
            firstSeen?: number | undefined;
            lastSeen?: number | undefined;
            mentionCount?: number | undefined;
        };
    } | undefined;
    processed_messages?: string[] | undefined;
    graph?: {
        nodes: {
            [key: string]: {
                name: string;
                type: "PERSON" | "PLACE" | "ORGANIZATION" | "OBJECT" | "CONCEPT";
                description: string;
                mentions: number;
                embedding?: number[] | undefined;
                embedding_b64?: string | undefined;
                aliases?: string[] | undefined;
                _st_synced?: boolean | undefined;
            };
        };
        edges: {
            [key: string]: {
                source: string;
                target: string;
                description: string;
                weight: number;
                _descriptionTokens?: number | undefined;
                embedding?: number[] | undefined;
                embedding_b64?: string | undefined;
                _st_synced?: boolean | undefined;
            };
        };
        _mergeRedirects?: {
            [key: string]: string;
        } | undefined;
        _edgesNeedingConsolidation?: string[] | undefined;
    } | undefined;
    communities?: {
        [key: string]: {
            id: string;
            title: string;
            summary: string;
            entities?: string[] | undefined;
            findings?: string[] | undefined;
            last_updated?: number | undefined;
        };
    } | undefined;
    reflection_state?: {
        lastMessageId?: number | undefined;
        reflectionCount?: number | undefined;
    } | undefined;
    graph_message_count?: number | undefined;
    global_world_state?: {
        summary: string;
        last_updated: number;
        community_count: number;
    } | undefined;
    embedding_model_id?: string | undefined;
};

export type StVectorItem = {
    hash: number;
    text: string;
    index?: number | undefined;
};

export type ScoringConfig = {
    forgetfulnessBaseLambda: number;
    forgetfulnessImportance5Floor: number;
    reflectionDecayThreshold: number;
    reflectionLevelMultiplier: number;
    vectorSimilarityThreshold: number;
    alpha: number;
    combinedBoostWeight: number;
    embeddingSource: "local" | "ollama" | "st_vector";
};

export type QueryConfig = {
    contextWindowSize?: number | undefined;
    entityBoostWeight?: number | undefined;
    corpusGroundedBoost?: number | undefined;
    corpusNonGroundedBoost?: number | undefined;
    exactPhraseBoostWeight?: number | undefined;
};

// End of generated types
